-- Imágenes OpenAI para el catálogo ficticio. Conserva imágenes personalizadas, stock y pedidos.
UPDATE products SET image='/images/products/generated/serum-facial-daily-glow.webp' WHERE slug='serum-facial-daily-glow' AND sku='FH-0001' AND image='/images/products/serum-facial-daily-glow.svg';
UPDATE supplier_products SET image='/images/products/generated/serum-facial-daily-glow.webp' WHERE code='PRV-00001' AND image='/images/products/serum-facial-daily-glow.svg';
UPDATE products SET image='/images/products/generated/crema-facial-soft-ritual.webp' WHERE slug='crema-facial-soft-ritual' AND sku='FH-0002' AND image='/images/products/crema-facial-soft-ritual.svg';
UPDATE supplier_products SET image='/images/products/generated/crema-facial-soft-ritual.webp' WHERE code='PRV-00002' AND image='/images/products/crema-facial-soft-ritual.svg';
UPDATE products SET image='/images/products/generated/gel-limpiador-pure-balance.webp' WHERE slug='gel-limpiador-pure-balance' AND sku='FH-0003' AND image='/images/products/gel-limpiador-pure-balance.svg';
UPDATE supplier_products SET image='/images/products/generated/gel-limpiador-pure-balance.webp' WHERE code='PRV-00003' AND image='/images/products/gel-limpiador-pure-balance.svg';
UPDATE products SET image='/images/products/generated/agua-micelar-fresh-moment.webp' WHERE slug='agua-micelar-fresh-moment' AND sku='FH-0004' AND image='/images/products/agua-micelar-fresh-moment.svg';
UPDATE supplier_products SET image='/images/products/generated/agua-micelar-fresh-moment.webp' WHERE code='PRV-00004' AND image='/images/products/agua-micelar-fresh-moment.svg';
UPDATE products SET image='/images/products/generated/balsamo-labial-velvet.webp' WHERE slug='balsamo-labial-velvet' AND sku='FH-0005' AND image='/images/products/balsamo-labial-velvet.svg';
UPDATE supplier_products SET image='/images/products/generated/balsamo-labial-velvet.webp' WHERE code='PRV-00005' AND image='/images/products/balsamo-labial-velvet.svg';
UPDATE products SET image='/images/products/generated/crema-corporal-botanical.webp' WHERE slug='crema-corporal-botanical' AND sku='FH-0006' AND image='/images/products/crema-corporal-botanical.svg';
UPDATE supplier_products SET image='/images/products/generated/crema-corporal-botanical.webp' WHERE code='PRV-00006' AND image='/images/products/crema-corporal-botanical.svg';
UPDATE products SET image='/images/products/generated/aceite-corporal-golden-hour.webp' WHERE slug='aceite-corporal-golden-hour' AND sku='FH-0007' AND image='/images/products/aceite-corporal-golden-hour.svg';
UPDATE supplier_products SET image='/images/products/generated/aceite-corporal-golden-hour.webp' WHERE code='PRV-00007' AND image='/images/products/aceite-corporal-golden-hour.svg';
UPDATE products SET image='/images/products/generated/locion-corporal-everyday.webp' WHERE slug='locion-corporal-everyday' AND sku='FH-0008' AND image='/images/products/locion-corporal-everyday.svg';
UPDATE supplier_products SET image='/images/products/generated/locion-corporal-everyday.webp' WHERE code='PRV-00008' AND image='/images/products/locion-corporal-everyday.svg';
UPDATE products SET image='/images/products/generated/crema-de-manos-cotton.webp' WHERE slug='crema-de-manos-cotton' AND sku='FH-0009' AND image='/images/products/crema-de-manos-cotton.svg';
UPDATE supplier_products SET image='/images/products/generated/crema-de-manos-cotton.webp' WHERE code='PRV-00009' AND image='/images/products/crema-de-manos-cotton.svg';
UPDATE products SET image='/images/products/generated/manteca-corporal-calm-texture.webp' WHERE slug='manteca-corporal-calm-texture' AND sku='FH-0010' AND image='/images/products/manteca-corporal-calm-texture.svg';
UPDATE supplier_products SET image='/images/products/generated/manteca-corporal-calm-texture.webp' WHERE code='PRV-00010' AND image='/images/products/manteca-corporal-calm-texture.svg';
UPDATE products SET image='/images/products/generated/champu-dermocare.webp' WHERE slug='champu-dermocare' AND sku='FH-0011' AND image='/images/products/champu-dermocare.svg';
UPDATE supplier_products SET image='/images/products/generated/champu-dermocare.webp' WHERE code='PRV-00011' AND image='/images/products/champu-dermocare.svg';
UPDATE products SET image='/images/products/generated/acondicionador-silk-routine.webp' WHERE slug='acondicionador-silk-routine' AND sku='FH-0012' AND image='/images/products/acondicionador-silk-routine.svg';
UPDATE supplier_products SET image='/images/products/generated/acondicionador-silk-routine.webp' WHERE code='PRV-00012' AND image='/images/products/acondicionador-silk-routine.svg';
UPDATE products SET image='/images/products/generated/mascarilla-capilar-sunday.webp' WHERE slug='mascarilla-capilar-sunday' AND sku='FH-0013' AND image='/images/products/mascarilla-capilar-sunday.svg';
UPDATE supplier_products SET image='/images/products/generated/mascarilla-capilar-sunday.webp' WHERE code='PRV-00013' AND image='/images/products/mascarilla-capilar-sunday.svg';
UPDATE products SET image='/images/products/generated/aceite-de-puntas-gloss.webp' WHERE slug='aceite-de-puntas-gloss' AND sku='FH-0014' AND image='/images/products/aceite-de-puntas-gloss.svg';
UPDATE supplier_products SET image='/images/products/generated/aceite-de-puntas-gloss.webp' WHERE code='PRV-00014' AND image='/images/products/aceite-de-puntas-gloss.svg';
UPDATE products SET image='/images/products/generated/champu-solido-fresh-leaf.webp' WHERE slug='champu-solido-fresh-leaf' AND sku='FH-0015' AND image='/images/products/champu-solido-fresh-leaf.svg';
UPDATE supplier_products SET image='/images/products/generated/champu-solido-fresh-leaf.webp' WHERE code='PRV-00015' AND image='/images/products/champu-solido-fresh-leaf.svg';
UPDATE products SET image='/images/products/generated/gel-de-ducha-citrus.webp' WHERE slug='gel-de-ducha-citrus' AND sku='FH-0016' AND image='/images/products/gel-de-ducha-citrus.svg';
UPDATE supplier_products SET image='/images/products/generated/gel-de-ducha-citrus.webp' WHERE code='PRV-00016' AND image='/images/products/gel-de-ducha-citrus.svg';
UPDATE products SET image='/images/products/generated/jabon-de-manos-green-tea.webp' WHERE slug='jabon-de-manos-green-tea' AND sku='FH-0017' AND image='/images/products/jabon-de-manos-green-tea.svg';
UPDATE supplier_products SET image='/images/products/generated/jabon-de-manos-green-tea.webp' WHERE code='PRV-00017' AND image='/images/products/jabon-de-manos-green-tea.svg';
UPDATE products SET image='/images/products/generated/pasta-dental-fresh-mint.webp' WHERE slug='pasta-dental-fresh-mint' AND sku='FH-0018' AND image='/images/products/pasta-dental-fresh-mint.svg';
UPDATE supplier_products SET image='/images/products/generated/pasta-dental-fresh-mint.webp' WHERE code='PRV-00018' AND image='/images/products/pasta-dental-fresh-mint.svg';
UPDATE products SET image='/images/products/generated/desodorante-clean-roll.webp' WHERE slug='desodorante-clean-roll' AND sku='FH-0019' AND image='/images/products/desodorante-clean-roll.svg';
UPDATE supplier_products SET image='/images/products/generated/desodorante-clean-roll.webp' WHERE code='PRV-00019' AND image='/images/products/desodorante-clean-roll.svg';
UPDATE products SET image='/images/products/generated/pack-cepillos-soft-touch.webp' WHERE slug='pack-cepillos-soft-touch' AND sku='FH-0020' AND image='/images/products/pack-cepillos-soft-touch.svg';
UPDATE supplier_products SET image='/images/products/generated/pack-cepillos-soft-touch.webp' WHERE code='PRV-00020' AND image='/images/products/pack-cepillos-soft-touch.svg';
UPDATE products SET image='/images/products/generated/gel-de-bano-little-cloud.webp' WHERE slug='gel-de-bano-little-cloud' AND sku='FH-0021' AND image='/images/products/gel-de-bano-little-cloud.svg';
UPDATE supplier_products SET image='/images/products/generated/gel-de-bano-little-cloud.webp' WHERE code='PRV-00021' AND image='/images/products/gel-de-bano-little-cloud.svg';
UPDATE products SET image='/images/products/generated/locion-infantil-sweet-moments.webp' WHERE slug='locion-infantil-sweet-moments' AND sku='FH-0022' AND image='/images/products/locion-infantil-sweet-moments.svg';
UPDATE supplier_products SET image='/images/products/generated/locion-infantil-sweet-moments.webp' WHERE code='PRV-00022' AND image='/images/products/locion-infantil-sweet-moments.svg';
UPDATE products SET image='/images/products/generated/balsamo-de-panal-baby-soft.webp' WHERE slug='balsamo-de-panal-baby-soft' AND sku='FH-0023' AND image='/images/products/balsamo-de-panal-baby-soft.svg';
UPDATE supplier_products SET image='/images/products/generated/balsamo-de-panal-baby-soft.webp' WHERE code='PRV-00023' AND image='/images/products/balsamo-de-panal-baby-soft.svg';
UPDATE products SET image='/images/products/generated/toallitas-cotton-cloud.webp' WHERE slug='toallitas-cotton-cloud' AND sku='FH-0024' AND image='/images/products/toallitas-cotton-cloud.svg';
UPDATE supplier_products SET image='/images/products/generated/toallitas-cotton-cloud.webp' WHERE code='PRV-00024' AND image='/images/products/toallitas-cotton-cloud.svg';
UPDATE products SET image='/images/products/generated/cepillo-infantil-soft-wood.webp' WHERE slug='cepillo-infantil-soft-wood' AND sku='FH-0025' AND image='/images/products/cepillo-infantil-soft-wood.svg';
UPDATE supplier_products SET image='/images/products/generated/cepillo-infantil-soft-wood.webp' WHERE code='PRV-00025' AND image='/images/products/cepillo-infantil-soft-wood.svg';
UPDATE products SET image='/images/products/generated/infusion-rooibos-naranja.webp' WHERE slug='infusion-rooibos-naranja' AND sku='FH-0026' AND image='/images/products/infusion-rooibos-naranja.svg';
UPDATE supplier_products SET image='/images/products/generated/infusion-rooibos-naranja.webp' WHERE code='PRV-00026' AND image='/images/products/infusion-rooibos-naranja.svg';
UPDATE products SET image='/images/products/generated/granola-avena-cacao.webp' WHERE slug='granola-avena-cacao' AND sku='FH-0027' AND image='/images/products/granola-avena-cacao.svg';
UPDATE supplier_products SET image='/images/products/generated/granola-avena-cacao.webp' WHERE code='PRV-00027' AND image='/images/products/granola-avena-cacao.svg';
UPDATE products SET image='/images/products/generated/infusion-de-frutos-del-bosque.webp' WHERE slug='infusion-de-frutos-del-bosque' AND sku='FH-0028' AND image='/images/products/infusion-de-frutos-del-bosque.svg';
UPDATE supplier_products SET image='/images/products/generated/infusion-de-frutos-del-bosque.webp' WHERE code='PRV-00028' AND image='/images/products/infusion-de-frutos-del-bosque.svg';
UPDATE products SET image='/images/products/generated/mix-de-semillas-natural.webp' WHERE slug='mix-de-semillas-natural' AND sku='FH-0029' AND image='/images/products/mix-de-semillas-natural.svg';
UPDATE supplier_products SET image='/images/products/generated/mix-de-semillas-natural.webp' WHERE code='PRV-00029' AND image='/images/products/mix-de-semillas-natural.svg';
UPDATE products SET image='/images/products/generated/te-verde-everyday.webp' WHERE slug='te-verde-everyday' AND sku='FH-0030' AND image='/images/products/te-verde-everyday.svg';
UPDATE supplier_products SET image='/images/products/generated/te-verde-everyday.webp' WHERE code='PRV-00030' AND image='/images/products/te-verde-everyday.svg';
UPDATE products SET image='/images/products/generated/almohadilla-de-semillas-linen.webp' WHERE slug='almohadilla-de-semillas-linen' AND sku='FH-0031' AND image='/images/products/almohadilla-de-semillas-linen.svg';
UPDATE supplier_products SET image='/images/products/generated/almohadilla-de-semillas-linen.webp' WHERE code='PRV-00031' AND image='/images/products/almohadilla-de-semillas-linen.svg';
UPDATE products SET image='/images/products/generated/aceite-de-masaje-slow-living.webp' WHERE slug='aceite-de-masaje-slow-living' AND sku='FH-0032' AND image='/images/products/aceite-de-masaje-slow-living.svg';
UPDATE supplier_products SET image='/images/products/generated/aceite-de-masaje-slow-living.webp' WHERE code='PRV-00032' AND image='/images/products/aceite-de-masaje-slow-living.svg';
UPDATE products SET image='/images/products/generated/antifaz-de-descanso-soft-night.webp' WHERE slug='antifaz-de-descanso-soft-night' AND sku='FH-0033' AND image='/images/products/antifaz-de-descanso-soft-night.svg';
UPDATE supplier_products SET image='/images/products/generated/antifaz-de-descanso-soft-night.webp' WHERE code='PRV-00033' AND image='/images/products/antifaz-de-descanso-soft-night.svg';
UPDATE products SET image='/images/products/generated/sales-de-bano-evening.webp' WHERE slug='sales-de-bano-evening' AND sku='FH-0034' AND image='/images/products/sales-de-bano-evening.svg';
UPDATE supplier_products SET image='/images/products/generated/sales-de-bano-evening.webp' WHERE code='PRV-00034' AND image='/images/products/sales-de-bano-evening.svg';
UPDATE products SET image='/images/products/generated/neceser-de-viaje-essential.webp' WHERE slug='neceser-de-viaje-essential' AND sku='FH-0035' AND image='/images/products/neceser-de-viaje-essential.svg';
UPDATE supplier_products SET image='/images/products/generated/neceser-de-viaje-essential.webp' WHERE code='PRV-00035' AND image='/images/products/neceser-de-viaje-essential.svg';
UPDATE products SET image='/images/products/generated/plantillas-de-confort-daily.webp' WHERE slug='plantillas-de-confort-daily' AND sku='FH-0036' AND image='/images/products/plantillas-de-confort-daily.svg';
UPDATE supplier_products SET image='/images/products/generated/plantillas-de-confort-daily.webp' WHERE code='PRV-00036' AND image='/images/products/plantillas-de-confort-daily.svg';
UPDATE products SET image='/images/products/generated/cojin-de-asiento-comfort.webp' WHERE slug='cojin-de-asiento-comfort' AND sku='FH-0037' AND image='/images/products/cojin-de-asiento-comfort.svg';
UPDATE supplier_products SET image='/images/products/generated/cojin-de-asiento-comfort.webp' WHERE code='PRV-00037' AND image='/images/products/cojin-de-asiento-comfort.svg';
UPDATE products SET image='/images/products/generated/banda-elastica-easy-move.webp' WHERE slug='banda-elastica-easy-move' AND sku='FH-0038' AND image='/images/products/banda-elastica-easy-move.svg';
UPDATE supplier_products SET image='/images/products/generated/banda-elastica-easy-move.webp' WHERE code='PRV-00038' AND image='/images/products/banda-elastica-easy-move.svg';
UPDATE products SET image='/images/products/generated/rodillera-textil-active.webp' WHERE slug='rodillera-textil-active' AND sku='FH-0039' AND image='/images/products/rodillera-textil-active.svg';
UPDATE supplier_products SET image='/images/products/generated/rodillera-textil-active.webp' WHERE code='PRV-00039' AND image='/images/products/rodillera-textil-active.svg';
UPDATE products SET image='/images/products/generated/pelota-de-masaje-soft-move.webp' WHERE slug='pelota-de-masaje-soft-move' AND sku='FH-0040' AND image='/images/products/pelota-de-masaje-soft-move.svg';
UPDATE supplier_products SET image='/images/products/generated/pelota-de-masaje-soft-move.webp' WHERE code='PRV-00040' AND image='/images/products/pelota-de-masaje-soft-move.svg';
UPDATE products SET image='/images/products/generated/locion-solar-daily-sun.webp' WHERE slug='locion-solar-daily-sun' AND sku='FH-0041' AND image='/images/products/locion-solar-daily-sun.svg';
UPDATE supplier_products SET image='/images/products/generated/locion-solar-daily-sun.webp' WHERE code='PRV-00041' AND image='/images/products/locion-solar-daily-sun.svg';
UPDATE products SET image='/images/products/generated/fluido-facial-sun-ritual.webp' WHERE slug='fluido-facial-sun-ritual' AND sku='FH-0042' AND image='/images/products/fluido-facial-sun-ritual.svg';
UPDATE supplier_products SET image='/images/products/generated/fluido-facial-sun-ritual.webp' WHERE code='PRV-00042' AND image='/images/products/fluido-facial-sun-ritual.svg';
UPDATE products SET image='/images/products/generated/after-sun-golden-days.webp' WHERE slug='after-sun-golden-days' AND sku='FH-0043' AND image='/images/products/after-sun-golden-days.svg';
UPDATE supplier_products SET image='/images/products/generated/after-sun-golden-days.webp' WHERE code='PRV-00043' AND image='/images/products/after-sun-golden-days.svg';
UPDATE products SET image='/images/products/generated/stick-solar-pocket-sun.webp' WHERE slug='stick-solar-pocket-sun' AND sku='FH-0044' AND image='/images/products/stick-solar-pocket-sun.svg';
UPDATE supplier_products SET image='/images/products/generated/stick-solar-pocket-sun.webp' WHERE code='PRV-00044' AND image='/images/products/stick-solar-pocket-sun.svg';
UPDATE products SET image='/images/products/generated/balsamo-labial-sunny.webp' WHERE slug='balsamo-labial-sunny' AND sku='FH-0045' AND image='/images/products/balsamo-labial-sunny.svg';
UPDATE supplier_products SET image='/images/products/generated/balsamo-labial-sunny.webp' WHERE code='PRV-00045' AND image='/images/products/balsamo-labial-sunny.svg';
