import type { ChannelAnalytics } from '../../lib/channel-analytics';
import '../../styles/sync-controls.css';
const names:Record<string,string>={WEB:'Web FarmaHouse',AMAZON:'Amazon',MIRAVIA:'Miravia',CARREFOUR:'Carrefour',EBAY:'eBay'};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n/100);
const number=(n:number)=>n.toLocaleString('es-ES');
export function channelOverview(data:ChannelAnalytics,onlyMarketplaces=false) {
 const rows=data.totals.filter(c=>!onlyMarketplaces||c.channel!=='WEB');
 const total=rows.reduce((sum,c)=>sum+c.orders,0),revenue=rows.reduce((sum,c)=>sum+c.total_cents,0),pending=rows.reduce((sum,c)=>sum+c.pending,0);
 const max=Math.max(1,...data.days.map(d=>d.marketplaces+(onlyMarketplaces?0:d.web)));
 const chartLabel=`Pedidos diarios de los últimos siete días, hora de Madrid. ${data.days.map(d=>`${d.date}: ${onlyMarketplaces?'':`web ${d.web}, `}marketplaces ${d.marketplaces}`).join('; ')}.`;
 const chart=`<div class="channel-chart" role="img" aria-label="${esc(chartLabel)}"><div class="channel-chart-bars">${data.days.map(d=>`<div><div class="channel-chart-column"><span class="channel-bar-market" style="height:${d.marketplaces/max*100}%" title="${d.marketplaces} pedidos de marketplaces"></span>${onlyMarketplaces?'':`<span class="channel-bar-web" style="height:${d.web/max*100}%" title="${d.web} pedidos web"></span>`}</div><strong>${onlyMarketplaces?d.marketplaces:d.web+d.marketplaces}</strong><small>${d.date.slice(8)}/${d.date.slice(5,7)}</small><span class="sr-only">${d.date}: web ${d.web}, marketplaces ${d.marketplaces}.</span></div>`).join('')}</div><p><i class="market-key"></i>Marketplaces ${onlyMarketplaces?'':'<i class="web-key"></i>Web'}<span>Últimos 7 días · Madrid</span></p></div>`;
 const recent=(web:boolean)=>{
  const list=data.recent.filter(order=>(order.channel==='WEB')===web);const group=data.totals.filter(c=>(c.channel==='WEB')===web);
  const count=group.reduce((n,c)=>n+c.orders,0),amount=group.reduce((n,c)=>n+c.total_cents,0);
  return `<section class="admin-card origin-card ${web?'origin-web':'origin-market'}"><div class="card-heading"><div><span class="section-kicker">${web?'CANAL DIRECTO':'CANALES EXTERNOS'}</span><h2>${web?'Pedidos de la web':'Pedidos de marketplaces'}</h2></div><strong class="origin-count">${number(count)}</strong></div><div class="origin-summary"><span>${money(amount)} de importe simulado</span><a href="${web?'/admin/pedidos?channel=WEB':'/admin/integraciones/lighthouse'}" class="text-link">${web?'Ver historial':'Ver por marketplace'} ↗</a></div><ul class="origin-orders">${list.map(o=>`<li><a href="/admin/pedidos/${o.id}"><span><strong>${esc(o.order_number)}</strong><small>${esc(names[o.channel])} · ${esc(new Date(o.created_at.includes('T')?o.created_at:o.created_at.replace(' ','T')+'Z').toLocaleString('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}))}</small></span><b>${money(o.total_cents)}</b></a></li>`).join('')||'<li class="muted">Todavía no hay pedidos de este origen.</li>'}</ul></section>`;
 };
 if(!onlyMarketplaces)return `<div class="origin-grid">${recent(true)}${recent(false)}</div><section class="admin-card channel-activity"><div class="card-heading"><h2>Entrada de pedidos</h2><span class="section-kicker">WEB + MARKETPLACES</span></div>${chart}</section>`;
 return `<section class="admin-card channel-activity marketplace-activity"><div class="card-heading"><h2>Pedidos de marketplaces</h2><span class="section-kicker">HISTÓRICO COMPLETO</span></div><div class="sync-stat-grid"><div><strong>${number(total)}</strong><span>Pedidos recibidos</span></div><div><strong>${money(revenue)}</strong><span>Importe simulado</span></div><div><strong>${money(total?Math.round(revenue/total):0)}</strong><span>Importe medio</span></div><div><strong>${number(pending)}</strong><span>Pendientes de proveedor</span></div></div><details id="marketplace-trend" class="marketplace-trend" data-panel-disclosure><summary>Actividad de los últimos 7 días<span aria-hidden="true">⌄</span></summary>${chart}</details></section>`;
}
